### ISSUE TITLE
TRANSACTION TIMED OUT:Getting error while executing cookiejar.py bake 100

### ISSUE THREAD

**Issue by sudamerushabh** [danintel/sawtooth-cookiejar#3]
`root@d044256bbb25:/project/cookiejar/pyclient# cookiejar.py bake 100 
URL to send to REST API is http://rest-api:8008/batches
[14:33:40 INFO    connectionpool] Starting new HTTP connection (1): rest-api
[14:33:40 DEBUG   connectionpool] "POST /batches HTTP/1.1" 202 183
URL to send to REST API is http://rest-api:8008/batch_statuses?id=f37fd087f8cfdf73fa3a28d9773b99732c60a2a920fea10828cd4df499b10cca55dd76c086c8f4b28078a017f34734040130ed43666340fd2e72a5b4e8f4e73b&wait=10
[14:33:40 INFO    connectionpool] Starting new HTTP connection (1): rest-api
[14:33:50 DEBUG   connectionpool] "GET /batch_statuses?id=f37fd087f8cfdf73fa3a28d9773b99732c60a2a920fea10828cd4df499b10cca55dd76c086c8f4b28078a017f34734040130ed43666340fd2e72a5b4e8f4e73b&wait=10 HTTP/1.1" 200 424
Bake Response: Transaction timed out after waiting 10 seconds.
`
Transaction Timed our error.
Any Solution on this??

**Comment by danintel** [comment]
My guess is the Cookiejar TP is not running, so the transaction is never processed.  What is the output of “sudo docker ps” ?
Here is my output:

$ sudo docker ps
[sudo] password for dano:
CONTAINER ID        IMAGE                                  COMMAND                   CREATED             STATUS              PORTS                              NAMES
3dbdcfd6f85e        sawtooth-cookiejar_cookiejar-client    "bash -c 'sawtooth k…"    5 weeks ago         Up About a minute   0.0.0.0:3000->3000/tcp             cookiejar-client
f3a1a61dd4c3        hyperledger/sawtooth-rest-api:1.0      "sawtooth-rest-api -…"    5 weeks ago         Up About a minute   4004/tcp, 0.0.0.0:8008->8008/tcp   rest-api
bea38cade10d        hyperledger/sawtooth-settings-tp:1.0   "settings-tp -vv --c…"    5 weeks ago         Up About a minute   4004/tcp                           sawtooth-cookiejar_settings-tp_1
70d4f215d96b        hyperledger/sawtooth-validator:1.0     "bash -c '\n  if [ ! …"   5 weeks ago         Up About a minute   0.0.0.0:4004->4004/tcp             validator

The cookiejar client should be running. Look in the messages for errors starting docker-compose .

Dan

**Comment by sudamerushabh** [comment]
There is Indentation error in file cookiejar_tp.py on line 169. That's why the transaction processor was not working. Thank you. And please make video tutorial on this project if possible. There is no content on internet to understand and deploy applications on sawtooth except docs which gives us only half understanding.

**Comment by danintel** [comment]
Rushabh,

Someone else fixed the indentation error, but thanks for letting me know.

I have a presentation on application development that I need to record. In the meantime, here is a PDF of the presentation.

Dan
