### ISSUE TITLE
NameError: name 'traceback' is not defined

### ISSUE THREAD

**Issue by harunurkst** [danintel/sawtooth-cookiejar#6]
when I executing cookiejar_tp.py in dev mode it shows error 
```
Traceback (most recent call last):
  File "cookiejar_tp.py", line 214, in <module>
    main()
  File "cookiejar_tp.py", line 210, in main
    traceback.print_exc(file=sys.stderr)
NameError: name 'traceback' is not defined
```
traceback and sys should import on top of the file
```
import traceback
import sys
```

**Comment by danintel** [comment]
Fix is:

```
diff --git a/pyprocessor/cookiejar_tp.py b/pyprocessor/cookiejar_tp.py
index 6a60394..1d213f8 100755
--- a/pyprocessor/cookiejar_tp.py
+++ b/pyprocessor/cookiejar_tp.py
@@ -16,6 +16,8 @@
 CookieJarTransactionHandler class interfaces for cookiejar Transaction Family.
 '''
 
+import traceback
+import sys
 import hashlib
 import logging
 
```

**Comment by danintel** [comment]
Fixed by push c7967e7

**Comment by yasinaziz** [comment]
selectedCrisis = "Women's March"

# Determine host-specific location of data
tweetDirectory = crisisInfo[selectedCrisis]["directory"]
tweetGlobPath = os.path.sep + os.path.join("Users", "nurmuhamad", "Desktop", "INST728 E",
                             "Dataset_women'smarch",tweetDirectory,"part-00*.gz")

print ("Reading files from:", tweetGlobPath)

# Dictionary for mapping dates to data
frequencyMap = {}

# Twitter's time format, for parsing the created_at date
timeFormat = "%a %b %d %H:%M:%S +0000 %Y"

for tweetFilePath in glob.glob(tweetGlobPath):
    print ("Reading File:", tweetFilePath)

    for line in gzip.open(tweetFilePath, 'rb'):

        # Convert from bytes to UTF8 string
        decoded_line = line.decode("utf8")
        
        # Try to read tweet JSON into object
        tweetObj = None
        try:
            tweetObj = json.loads(decoded_line)
        except json.JSONDecodeError as jde:
            print("JSON Decode Error:", decoded_line)
            continue

        # Deleted status messages and protected status must be skipped
        if ( "delete" in tweetObj.keys() or "status_withheld" in tweetObj.keys() ):
            continue

        # Try to extract the time of the tweet
        try:
            currentTime = datetime.datetime.strptime(tweetObj['created_at'], timeFormat)
        except:
            print("Error parsing time on line:", decoded_line)
            raise

        # Flatten this tweet's time
        currentTime = currentTime.replace(second=0)

        # If our frequency map already has this time, use it, otherwise add
        extended_list = frequencyMap.get(currentTime, [])
        extended_list.append(tweetObj)
        frequencyMap[currentTime] = extended_list

![image](https://user-images.githubusercontent.com/34503256/62557942-95483800-b8aa-11e9-9195-e15437c9993a.png)

**Comment by yasinaziz** [comment]
why this cannot run
