### ISSUE TITLE
Error running docker-compose-go-event-client

### ISSUE THREAD

**Issue by rubenaraujo** [danintel/sawtooth-cookiejar#8]
When doing the go generate the follow error appears:

`Loading input failed: unsupported version of go: exit status 2: flag provided but not defined: -compiled`

**Comment by sanjibbaral435** [comment]
Facing the exact same issue.

**Comment by danintel** [comment]
PR #9 updated Go from 1.9 to 1.11.  That may help.
Let me know if it works or not.

**Comment by arsulegai** [comment]
This is the same issue that I faced and hence the PR #9 .
